CREATE TABLE notes (
  id SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  content TEXT NOT NULL,
  modified TIMESTAMP DEFAULT now() NOT NULL,
  folder_id INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL
);
